python3 ConstraintSolver.py BACKTRACK Class_v.txt
python3 ConstraintSolver.py BACKTRACK Map_u.txt
python3 ConstraintSolver.py BACKTRACK Map_v.txt
python3 ConstraintSolver.py BACKTRACK Sudoku_v2.txt
python3 ConstraintSolver.py BACKTRACK Zebra.txt
python3 ConstraintSolver.py MINCONFLICTS Class_v.txt
python3 ConstraintSolver.py MINCONFLICTS Map_u.txt
python3 ConstraintSolver.py MINCONFLICTS Map_v.txt
python3 ConstraintSolver.py MINCONFLICTS Sudoku_v2.txt
python3 ConstraintSolver.py MINCONFLICTS Zebra.txt